[package]
name = "alan/rex"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
react = "jsdotlua/react@17.2.0"
react-roblox = "jsdotlua/react-roblox@17.2.0"
reactflow = "mewious/reactflow@0.1.1"